version: '3'
services:
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    restart: on-failure

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - monitor-storage:/prometheus
      - ./prometheus:/etc/prometheus/
    restart: on-failure

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: on-failure
    depends_on:
    - prometheus
   
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: on-failure

volumes:
 monitor-storage:
