version: '3'
services:
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    restart: on-failure

  prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    user: "1000"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    restart: on-failure

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    
  node-exporter:
    image: prom/node-exporter
    container_name: my-node-exporter
    restart: on-failure
    depends_on:
    - prometheus
   
  grafana:
    image: grafana/grafana
    user: "1000"
    container_name: my-grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: on-failure
    depends_on:
    - prometheus
